version: '3.8'

services:
  mcp-expokossodo:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST:-to1.fcomet.com}
      - DB_USER=${DB_USER:-atusalud_atusalud}
      - DB_PASSWORD=${DB_PASSWORD:-kmachin1}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-atusalud_kossomet}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-super-secret-jwt-key-change-this}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - expokossodo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - expokossodo-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis_data:

networks:
  expokossodo-network:
    driver: bridge